# Secrets:
# RELEASE_TOKEN = write permission token

name: build

on:
  workflow_dispatch:
  push: { branches: [ main ] }

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-jq
            mingw-w64-ucrt-x86_64-rust
            mingw-w64-ucrt-x86_64-openssl
      - name: build
        shell: msys2 {0}
        run: |
          mkdir build; cd build
          curl -fsSL "$( curl -fsSL 'https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest' | jq -Mrc '.tarball_url' )" |
          MSYS='winsymlinks:lnk' tar -xz --strip-components=1
          OPENSSL_DIR="$( cygpath -aw /ucrt64 )" RUSTFLAGS="--remap-path-prefix=${USERPROFILE}=~" cargo build --features sqlite --release
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        shell: bash -eo pipefail {0}
        run: |
          bin='build/target/release/vaultwarden.exe'
          ! gh release view result &>/dev/null &&
          gh release create result "${bin}" -n 'download here' ||
          gh release upload result "${bin}" --clobber
